return {
	{ text = "As seen on TV!", author = nil },
	{ text = "Awesome!", author = nil },
	{ text = "100% pure!", author = nil },
	{ text = "May contain nuts!", author = nil },
	{ text = "More polygons!", author = nil },
	{ text = "Moderately attractive!", author = nil },
	{ text = "Limited edition!", author = nil },
	{ text = "Flashing letters!", author = nil },
	{ text = "It's here!", author = nil },
	{ text = "Best in class!", author = nil },
	{ text = "It's finished!", author = nil },
	{ text = "Kind of dragon free!", author = nil },
	{ text = "Excitement!", author = nil },
	{ text = "More than 500 sold!", author = nil },
	{ text = "One of a kind!", author = nil },
	{ text = "Heaps of hits on YouTube!", author = nil },
	{ text = "Indev!", author = nil },
	{ text = "Spiders everywhere!", author = nil },
	{ text = "Check it out!", author = nil },
	{ text = "Holy cow, man!", author = nil },
	{ text = "It's a game!", author = nil },
	{ text = "Made in Sweden!", author = nil },
	{ text = "Uses LWJGL!", author = nil },
	{ text = "Reticulating splines!", author = nil },
	{ text = "Minecraft!", author = nil },
	{ text = "Yaaay!", author = nil },
	{ text = "Singleplayer!", author = nil },
	{ text = "Keyboard compatible!", author = nil },
	{ text = "Ingots!", author = nil },
	{ text = "Exploding creepers!", author = nil },
	{ text = "That's no moon!", author = nil },
	{ text = "l33t!", author = nil },
	{ text = "Create!", author = nil },
	{ text = "Survive!", author = nil },
	{ text = "Dungeon!", author = nil },
	{ text = "Exclusive!", author = nil },
	{ text = "The bee's knees!", author = nil },
	{ text = "Closed source!", author = nil },
	{ text = "Classy!", author = nil },
	{ text = "Wow!", author = nil },
	{ text = "Not on Steam!", author = nil },
	{ text = "Oh man!", author = nil },
	{ text = "Awesome community!", author = nil },
	{ text = "Pixels!", author = nil },
	{ text = "Teetsuuuuoooo!", author = nil },
	{ text = "Kaaneeeedaaaa!", author = nil },
	{ text = "Now with difficulty!", author = nil },
	{ text = "Enhanced!", author = nil },
	{ text = "90% bug free!", author = nil },
	{ text = "Pretty!", author = nil },
	{ text = "12 herbs and spices!", author = nil },
	{ text = "Fat free!", author = nil },
	{ text = "Absolutely no memes!", author = nil },
	{ text = "Free dental!", author = nil },
	{ text = "Ask your doctor!", author = nil },
}
