return {
  quotes = {
    { text = "As seen on TV!", author = nil },
    { text = "Awesome!", author = nil },
    { text = "100% pure!", author = nil },
    { text = "May contain nuts!", author = nil },
    { text = "More polygons!‌[JE  only]Less polygons!‌[BE  only]", author = nil },
    { text = "Moderately attractive!", author = nil },
    { text = "Limited edition!", author = nil },
    { text = "Flashing letters!", author = nil },
    { text = "It's here!", author = nil },
    { text = "Best in class!", author = nil },
    { text = "It's finished!", author = nil },
    { text = "Kind of dragon free!", author = nil },
    { text = "Excitement!", author = nil },
    { text = "More than 500 sold!", author = nil },
    { text = "One of a kind!", author = nil },
    { text = "Heaps of hits on YouTube!", author = nil },
    { text = "Indev!", author = nil },
    { text = "Spiders everywhere!", author = nil },
    { text = "Check it out!", author = nil },
    { text = "Holy cow, man!", author = nil },
    { text = "It's a game!", author = nil },
    { text = "Made in Sweden!", author = nil },
    { text = "Uses LWJGL!", author = nil },
    { text = "Reticulating splines!", author = nil },
    { text = "Minecraft!", author = nil },
    { text = "Yaaay!", author = nil },
    { text = "Singleplayer!", author = nil },
    { text = "Keyboard compatible!", author = nil },
    { text = "Ingots!", author = nil },
    { text = "Exploding creepers!", author = nil },
    { text = "That's no moon!", author = nil },
    { text = "l33t!", author = nil },
    { text = "Create!", author = nil },
    { text = "Survive!", author = nil },
    { text = "Dungeon!", author = nil },
    { text = "Exclusive!", author = nil },
    { text = "The bee's knees!", author = nil },
    { text = "Closed source!", author = nil },
    { text = "Classy!", author = nil },
    { text = "Wow!", author = nil },
    { text = "Not on Steam!", author = nil },
    { text = "Oh man!", author = nil },
    { text = "Awesome community!", author = nil },
    { text = "Pixels!", author = nil },
    { text = "Teetsuuuuoooo!", author = nil },
    { text = "Kaaneeeedaaaa!", author = nil },
    { text = "Now with difficulty!", author = nil },
    { text = "Enhanced!", author = nil },
    { text = "90% bug free!", author = nil },
    { text = "Pretty!", author = nil },
    { text = "12 herbs and spices!", author = nil },
    { text = "Fat free!", author = nil },
    { text = "Absolutely no memes!", author = nil },
    { text = "Free dental!", author = nil },
    { text = "Ask your doctor!", author = nil },
    { text = "Minors welcome!", author = nil },
    { text = "Cloud computing!", author = nil },
    { text = "Legal in Finland!", author = nil },
    { text = "Hard to label!", author = nil },
    { text = "Technically good!", author = nil },
    { text = "Bringing home the bacon!", author = nil },
    { text = "Indie!", author = nil },
    { text = "GOTY!", author = nil },
    { text = "Ceci n'est pas une title screen!", author = nil },
    { text = "Euclidian!  [sic]", author = nil },
    { text = "Now in 3D!", author = nil },
    { text = "Inspirational!", author = nil },
    { text = "Herregud!", author = nil },
    { text = "Complex cellular automata!", author = nil },
    { text = "Yes, sir!", author = nil },
    { text = "Played by cowboys!", author = nil },
    { text = "Now on OpenGL 3.2 core profile!", author = nil },
    { text = "Thousands of colors!", author = nil },
    { text = "Try it!", author = nil },
    { text = "Age of Wonders is better!", author = nil },
    { text = "Try the mushroom stew!", author = nil },
    { text = "Sensational!", author = nil },
    { text = "Hot tamale, hot hot tamale!", author = nil },
    { text = "Play him off, keyboard cat!", author = nil },
    { text = "Guaranteed!", author = nil },
    { text = "Macroscopic!", author = nil },
    { text = "Bring it on!", author = nil },
    { text = "Random splash!", author = nil },
    { text = "Call your mother!", author = nil },
    { text = "Monster infighting!", author = nil },
    { text = "Loved by millions!", author = nil },
    { text = "Ultimate edition!", author = nil },
    { text = "Freaky!", author = nil },
    { text = "You've got a brand new key!", author = nil },
    { text = "Water proof!", author = nil },
    { text = "Uninflammable!", author = nil },
    { text = "Whoa, dude!", author = nil },
    { text = "All inclusive!", author = nil },
    { text = "Tell your friends!", author = nil },
    { text = "NP is not in P!", author = nil },
    { text = "Music by C418!", author = nil },
    { text = "Livestreamed!", author = nil },
    { text = "Haunted!", author = nil },
    { text = "Polynomial!", author = nil },
    { text = "Terrestrial!", author = nil },
    { text = "All is full of love!", author = nil },
    { text = "Full of stars!", author = nil },
    { text = "Scientific!", author = nil },
    { text = "Not as cool as Spock!", author = nil },
    { text = "Collaborate and listen!", author = nil },
    { text = "Never dig down!", author = nil },
    { text = "Take frequent breaks!", author = nil },
    { text = "Not linear!", author = nil },
    { text = "Han shot first!", author = nil },
    { text = "Nice to meet you!", author = nil },
    { text = "Buckets of lava!", author = nil },
    { text = "Ride the pig!", author = nil },
    { text = "Larger than Earth!", author = nil },
    { text = "sqrt(-1) love you!", author = nil },
    { text = "Phobos anomaly!", author = nil },
    { text = "Punching wood!", author = nil },
    { text = "Falling off cliffs!", author = nil },
    { text = "1% sugar!", author = nil },
    { text = "150% hyperbole!", author = nil },
    { text = "Synecdoche!", author = nil },
    { text = "Let's danec!", author = nil },
    { text = "Seecret Friday update!", author = nil },
    { text = "Reference implementation!", author = nil },
    { text = "Kiss the sky!", author = nil },
    { text = "20 GOTO 10!", author = nil },
    { text = "Verlet intregration!  [sic]", author = nil },
    { text = "Peter Griffin!", author = nil },
    { text = "Do not distribute!", author = nil },
    { text = "Cogito ergo sum!", author = nil },
    { text = "4815162342 lines of code!", author = nil },
    { text = "A skeleton popped out!", author = nil },
    { text = "The sum of its parts!", author = nil },
    { text = "BTAF used to be good!", author = nil },
    { text = "I miss ADOM!", author = nil },
    { text = "umop-apisdn!", author = nil },
    { text = "OICU812!", author = nil },
    { text = "Bring me Ray Cokes!", author = nil },
    { text = "Finger-licking!", author = nil },
    { text = "Thematic!", author = nil },
    { text = "Pneumatic!", author = nil },
    { text = "Sublime!", author = nil },
    { text = "Octagonal!", author = nil },
    { text = "Une baguette!", author = nil },
    { text = "Gargamel plays it!", author = nil },
    { text = "Rita is the new top dog!", author = nil },
    { text = "SWM forever!", author = nil },
    { text = "Representing Edsbyn!", author = nil },
    { text = "Matt Damon!", author = nil },
    { text = "Supercalifragilisticexpialidocious!", author = nil },
    { text = "Consummate V's!", author = nil },
    { text = "Cow Tools!", author = nil },
    { text = "Double buffered!", author = nil },
    { text = "Fan fiction!", author = nil },
    { text = "Flaxkikare!", author = nil },
    { text = "Jason! Jason! Jason!‌[JE  only]Jason! Jason! Jason! Jeison?‌[BE  only]", author = nil },
    { text = "Hotter than the sun!", author = nil },
    { text = "Internet enabled!", author = nil },
    { text = "Autonomous!", author = nil },
    { text = "Engage!", author = nil },
    { text = "Fantasy!", author = nil },
    { text = "DRR! DRR! DRR!", author = nil },
    { text = "Kick it root down!", author = nil },
    { text = "Regional resources!", author = nil },
    { text = "Woo, facepunch!", author = nil },
    { text = "Woo, somethingawful!", author = nil },
    { text = "Woo, tigsource!", author = nil },
    { text = "Woo, worldofminecraft!", author = nil },
    { text = "Woo, reddit!", author = nil },
    { text = "Woo, 2pp!", author = nil },
    { text = "Google anlyticsed!", author = nil },
    { text = "Now supports åäö!", author = nil },
    { text = "Give us Gordon!", author = nil },
    { text = "Tip your waiter!", author = nil },
    { text = "Very fun!", author = nil },
    { text = "12345 is a bad password!", author = nil },
    { text = "Vote for net neutrality!", author = nil },
    { text = "Lives in a pineapple under the sea!", author = nil },
    { text = "MAP11 has two names!", author = nil },
    { text = "Omnipotent!", author = nil },
    { text = "Gasp!", author = nil },
    { text = "...!", author = nil },
    { text = "Bees, bees, bees, bees!", author = nil },
    { text = "Jag känner en bot!", author = nil },
    { text = "This text is hard to read if you play the game at the default resolution, but at 1080p it's fine!", author = nil },
    { text = "Haha, LOL!‌[JE  only]Haha, LEL!‌[BE  only]", author = nil },
    { text = "Hampsterdance!", author = nil },
    { text = "Menger sponge!", author = nil },
    { text = "idspispopd!", author = nil },
    { text = "Eple (original edit)!", author = nil },
    { text = "So fresh, so clean!", author = nil },
    { text = "Slow acting portals!", author = nil },
    { text = "Try the Nether!", author = nil },
    { text = "Don't look directly at the bugs!", author = nil },
    { text = "Oh, ok, Pigmen!", author = nil },
    { text = "Finally with ladders!", author = nil },
    { text = "Scary!", author = nil },
    { text = "Play Minecraft, Watch Topgear, Get Pig!", author = nil },
    { text = "Twittered about!", author = nil },
    { text = "Jump up, jump up, and get down!", author = nil },
    { text = "Joel is neat!", author = nil },
    { text = "A riddle, wrapped in a mystery!", author = nil },
    { text = "This parrot is no more! It has ceased to be!", author = nil },
    { text = "Welcome to your Doom!", author = nil },
    { text = "Stay a while, stay forever!", author = nil },
    { text = "Stay a while and listen!", author = nil },
    { text = "Treatment for your rash!", author = nil },
    { text = "Autological is!", author = nil },
    { text = "Information wants to be free!", author = nil },
    { text = '"Almost never" is an interesting concept!', author = nil },
    { text = "Lots of truthiness!", author = nil },
    { text = "The creeper is a spy!", author = nil },
    { text = "Turing complete!", author = nil },
    { text = "It's groundbreaking!", author = nil },
    { text = "Let our battle's begin!  [sic]", author = nil },
    { text = "The sky is the limit!", author = nil },
    { text = "Jeb has amazing hair!", author = nil },
    { text = "Ryan also has amazing hair!", author = nil },
    { text = "Casual gaming!", author = nil },
    { text = "Undefeated!", author = nil },
    { text = "Kinda like Lemmings!", author = nil },
    { text = "Follow the train, CJ!", author = nil },
    { text = "Leveraging synergy!", author = nil },
    { text = "This message will never appear on the splash screen, isn't that weird?", author = nil },
    { text = "DungeonQuest is unfair!", author = nil },
    { text = "90210!", author = nil },
    { text = "Check out the far lands!", author = nil },
    { text = "Tyrion would love it!", author = nil },
    { text = "Also try VVVVVV!", author = nil },
    { text = "Also try Super Meat Boy!", author = nil },
    { text = "Also try Terraria!", author = nil },
    { text = "Also try Mount And Blade!", author = nil },
    { text = "Also try Project Zomboid!", author = nil },
    { text = "Also try World of Goo!", author = nil },
    { text = "Also try Limbo!", author = nil },
    { text = "Also try Pixeljunk Shooter!", author = nil },
    { text = "Also try Braid!", author = nil },
    { text = "That's super!", author = nil },
    { text = "Bread is pain!", author = nil },
    { text = "Read more books!", author = nil },
    { text = "Khaaaaaaaaan!", author = nil },
    { text = "Less addictive than TV Tropes!", author = nil },
    { text = "More addictive than lemonade!", author = nil },
    { text = "Bigger than a bread box!", author = nil },
    { text = "Millions of peaches!", author = nil },
    { text = "Fnord!", author = nil },
    { text = "This is my true form!", author = nil },
    { text = "Don't bother with the clones!", author = nil },
    { text = "Pumpkinhead!", author = nil },
    { text = "Made by Jeb!", author = nil },
    { text = "Has an ending!", author = nil },
    { text = "Finally complete!", author = nil },
    { text = "Feature packed!", author = nil },
    { text = "Boots with the fur!", author = nil },
    { text = "Stop, hammertime!", author = nil },
    { text = "Testificates!", author = nil },
    { text = "Conventional!", author = nil },
    { text = "Homeomorphic to a 3-sphere!", author = nil },
    { text = "Doesn't avoid double negatives!", author = nil },
    { text = "Place ALL the blocks!", author = nil },
    { text = "Does barrel rolls!", author = nil },
    { text = "Meeting expectations!", author = nil },
    { text = "PC gaming since 1873!", author = nil },
    { text = "Ghoughpteighbteau tchoghs!", author = nil },
    { text = "Déjà vu! [N 3]", author = nil },
    { text = "Got your nose!", author = nil },
    { text = "Haley loves Elan!", author = nil },
    { text = "Afraid of the big, black bat!", author = nil },
    { text = "Doesn't use the U-word!", author = nil },
    { text = "Child's play!", author = nil },
    { text = "See you next Friday or so!", author = nil },
    { text = "From the streets of Södermalm!", author = nil },
    { text = "150 bpm for 400000 minutes!", author = nil },
    { text = "Technologic!", author = nil },
    { text = "Funk soul brother!", author = nil },
    { text = "Pumpa kungen!", author = nil },
    { text = "日本ハロー！", author = nil },
    { text = "한국 안녕하세요!", author = nil },
    { text = "Helo Cymru!", author = nil },
    { text = "Cześć Polsko!", author = nil },
    { text = "你好中国！", author = nil },
    { text = "Γεια σου Ελλάδα!", author = nil },
    { text = "My life for Aiur!", author = nil },
    { text = "Lennart lennart = new Lennart();", author = nil },
    { text = "I see your vocabulary has improved!", author = nil },
    { text = "Who put it there?", author = nil },
    { text = "You can't explain that!", author = nil },
    { text = "if not ok then return end", author = nil },
    { text = "Colormatic", author = nil },
    { text = "FUNKY LOL", author = nil },
    { text = "Big Pointy Teeth!", author = nil },
    { text = "Bekarton guards the gate!", author = nil },
    { text = "Mmmph, mmph!", author = nil },
    { text = "Don't feed avocados to parrots!", author = nil },
    { text = "Swords for everyone!", author = nil },
    { text = "Plz reply to my tweet!", author = nil },
    { text = ".party()!", author = nil },
    { text = "Take her pillow!", author = nil },
    { text = "Put that cookie down!", author = nil },
    { text = "Pretty scary!", author = nil },
    { text = "I have a suggestion.", author = nil },
    { text = "Now with extra hugs!", author = nil },
    { text = "Java 16 + 1 = 17!", author = nil },
    { text = "Woah.", author = nil },
    { text = "HURNERJSGER?", author = nil },
    { text = "What's up, Doc?", author = nil },
    { text = "Now contains 32 random daily cats!", author = nil },
    { text = "That's Numberwang!", author = nil },
    { text = "pls rt", author = nil },
    { text = "Do you want to join my server?", author = nil },
    { text = "Put a little fence around it!", author = nil },
    { text = "Throw a blanket over it!", author = nil },
    { text = "One day, somewhere in the future, my work will be quoted!", author = nil },
    { text = "Now with additional stuff!", author = nil },
    { text = "Extra things!", author = nil },
    { text = "Yay, puppies for everyone!", author = nil },
    { text = "So sweet, like a nice bon bon!", author = nil },
    { text = "Very influential in its circle!", author = nil },
    { text = "Now With Multiplayer!", author = nil },
    { text = "Rise from your grave!", author = nil },
    { text = 'Warning! A huge battleship "STEVE" is approaching fast!', author = nil },
    { text = "Blue warrior shot the food!", author = nil },
    { text = "Run, coward! I hunger!", author = nil },
    { text = "Flavor with no seasoning!", author = nil },
    { text = "Strange, but not a stranger!", author = nil },
    { text = "Tougher than diamonds, rich like cream!", author = nil },
    { text = "It swings, it jives!", author = nil },
    { text = "Cruising streets for gold!", author = nil },
    { text = "Take an eggbeater and beat it against a skillet!", author = nil },
    { text = "Make me a table, a funky table!", author = nil },
    { text = "Take the elevator to the mezzanine!", author = nil },
    { text = "Stop being reasonable, this is the Internet!", author = nil },
    { text = "/give @a hugs 64", author = nil },
    { text = "This is good for Realms.", author = nil },
    { text = "Any computer is a laptop if you're brave enough!", author = nil },
    { text = "Do it all, everything!", author = nil },
    { text = "Where there is not light, there can spider!", author = nil },
    { text = "GNU Terry Pratchett", author = nil },
    { text = "More Digital!", author = nil },
    { text = "doot doot!", author = nil },
    { text = "Falling with style!", author = nil },
    { text = "There's no stopping the Trollmaso", author = nil },
    { text = "Throw yourself at the ground and miss", author = nil },
    { text = "Rule #1: it's never my fault", author = nil },
    { text = "Replaced molten cheese with blood?", author = nil },
    { text = "Absolutely fixed relatively broken coordinates", author = nil },
    { text = "Boats FTW", author = nil },
    { text = "Javalicious edition", author = nil },
    { text = "Should not be played while driving", author = nil },
    { text = "You're going too fast!", author = nil },
    { text = "Don't feed chocolate to parrots!", author = nil },
    { text = "The true meaning of covfefe", author = nil },
    { text = "An illusion! What are you hiding?", author = nil },
    { text = "Something funny!", author = nil },
    { text = "Something's not quite right...", author = nil },
    { text = "Thank you for the fish!", author = nil },
    { text = "All rumors are true!", author = nil },
    { text = "Truly gone fishing!", author = nil },
    { text = "Rainbow turtle?", author = nil },
    { text = "I need more context.", author = nil },
    { text = "Ahhhhhh!", author = nil },
    { text = "Don't worry, be happy!", author = nil },
    { text = "Water bottle!", author = nil },
    { text = "What's the question?", author = nil },
    { text = "Plant a tree!", author = nil },
    { text = "Go to the dentist!", author = nil },
    { text = "What do you expect?", author = nil },
    { text = "Look mum, I'm in a splash!", author = nil },
    { text = "It came from space.", author = nil },
    { text = "Awesome game design right there!", author = nil },
    { text = "Ph1lza had a good run!", author = nil },
    { text = "10 years of Mining and Crafting!", author = nil },
    { text = "Ping the human!", author = nil },
    { text = "In case it isn't obvious, foxes aren't players.", author = nil },
    { text = "Buzzy Bees!", author = nil },
    { text = "Minecraft Java Edition presents: Disgusting Bugs", author = nil },
    { text = "Wash your hands!", author = nil },
    { text = "Soap and water!", author = nil },
    { text = "Support local businesses!", author = nil },
    { text = "Stay home and play games!", author = nil },
    { text = "Stay safe!", author = nil },
    { text = "Stay strong!", author = nil },
    { text = "Cough or sneeze into your elbow!", author = nil },
    { text = "Don’t  touch your face!", author = nil },
    { text = "Support elderly relatives and friends!", author = nil },
    { text = "Prepare, but don’t  hoard!", author = nil },
    { text = "Gamers unite – separately in your own homes!", author = nil },
    { text = "Save the world – stay inside!", author = nil },
    { text = "Shop for your elders!", author = nil },
    { text = "Hang out with your friends online!", author = nil },
    { text = "Honey, I grew the bees!‌[JE  only]Honey, I grew the bees‌[BE  only]", author = nil },
    { text = "Find your claw!", author = nil },
    { text = "Everybody do the Leif!", author = nil },
    { text = "<3 Max & 99 & Ducky!", author = nil },
    { text = "Bushy eyebrows!", author = nil },
    { text = "Edit is a name!‌[JE  only]Edit is a name‌[BE  only]", author = nil },
    { text = "From free range developers!", author = nil },
    { text = "Music by Lena Raine!", author = nil },
    { text = "Aww man!", author = nil },
    { text = "#minecraftfarms", author = nil },
    { text = "And my pickaxe!", author = nil },
    { text = "Envision! Create! Share!", author = nil },
    { text = "Fabulous graphics!", author = nil },
    { text = "Also try Minecraft Dungeons!", author = nil },
    { text = "Vanilla!", author = nil },
    { text = "May contain traces of citrus!", author = nil },
    { text = "Zoglin!?", author = nil },
    { text = "Black lives matter!", author = nil },
    { text = "Be anti-racist!", author = nil },
    { text = "Learn about allyship!", author = nil },
    { text = "Speak OUT against injustice and UP for equality!", author = nil },
    { text = "Amplify and listen to BIPOC voices!", author = nil },
    { text = "Educate your friends on anti-racism!", author = nil },
    { text = "Support the BIPOC community and creators!", author = nil },
    { text = "Stand up for equality in your community!", author = nil },
    { text = "[this splash text is now available]", author = nil },
    { text = "Contains simulated goats!", author = nil },
    { text = "Home-made!", author = nil },
    { text = "There's <<a cat on ,my keyboard!~ [sic]", author = nil },
    { text = "The cutest predator you'll ever meet!", author = nil },
    { text = "Now you are thinking with pistons!", author = nil },
    { text = "Get to the coppah!", author = nil },
    { text = "Board game version also available!", author = nil },
    { text = "Honey, I waxed the copper!", author = nil },
    { text = "Plant-based light sources!", author = nil },
    { text = 'Made by "real" people!', author = nil },
    { text = "Shriek like a Sculk Shrieker!", author = nil },
    { text = "Who let the frogs out?", author = nil },
    { text = "RIBBIT!", author = nil },
    { text = "Croak team!", author = nil },
    { text = "Nooooooooooooo!", author = nil },
    { text = "Flower forest TM perfume", author = nil },
    { text = "Hat Fridays!", author = nil },
    { text = "Technoblade never dies!", author = nil },
    { text = "You are valid!", author = nil },
    { text = "I'm glad you're here!", author = nil },
    { text = "You are welcome here!", author = nil },
    { text = "Your gender is valid!", author = nil },
    { text = "Contains infinite genders!", author = nil },
    { text = "Made with lave!", author = nil },
    { text = "This sand is sus", author = nil },
    { text = "Remember to brush your... ...teeth", author = nil },
    { text = "Has working bookshelves!", author = nil },
    { text = "Sniff sniff...", author = nil },
    { text = "Place hanging sign here", author = nil },
    { text = "Joule is neat too!", author = nil },
    { text = "Flint and Steel!", author = nil },
    { text = "Chicken Jockey!", author = nil },
    { text = "Teachers gonna teach", author = nil },
    { text = "An enderman stole my homework", author = nil },
    { text = "Kid tested, teacher approved!", author = nil },
    { text = "The creeper ate my homework!", author = nil },
    { text = "Diamonds! Nope, Lapis.", author = nil },
    { text = "22nd Century Skills!", author = nil },
    { text = "Make it rain! Now make it stop!", author = nil },
    { text = "Education for the win!", author = nil },
    { text = "Not too cool for school!", author = nil },
    { text = "Play! Teach! Learn!", author = nil },
    { text = "Get smarter!", author = nil },
    { text = "Smile for the camera!", author = nil },
    { text = "'C' is for Code Builder", author = nil },
    { text = "[this splash text is now available]", author = nil },
    { text = "1% sugar!", author = nil },
    { text = "Heaps of hits on YouTube!", author = nil },
    { text = "Kind of dragon free!", author = nil },
    { text = "Now Java 6!", author = nil },
    { text = "Now Java 8!", author = nil },
    { text = "Now Java 16!", author = nil },
    { text = "Java 16 + 1 = 17!", author = nil },
    { text = "It's here!", author = nil },
    { text = "Not as cool as Spock!", author = nil },
    { text = "Cześć Polsko!", author = nil },
    { text = "More than 25000 sold!", author = nil },
    { text = "More than 500 sold!", author = nil },
    { text = "Notch <3 ez!", author = nil },
    { text = 'Autological" is!', author = nil },
    { text = "Now supports åäö!", author = nil },
    { text = "OpenGL 1.2!", author = nil },
    { text = "OpenGL 2.1 (if supported)!", author = nil },
    { text = "Now on OpenGL 3.2 core profile!", author = nil },
    { text = "Lewd with two dudes with food!", author = nil },
    { text = "Moderately attractive!", author = nil },
    { text = "SOPA means LOSER in Swedish!", author = nil },
    { text = "Supercalifragilisticexpialidocious!", author = nil },
    { text = "That's no moon!", author = nil },
    { text = "This is good for Realms.", author = nil },
    { text = "Tyrion would love it!", author = nil },
    { text = "It's finished!", author = nil },
    { text = "100% more yellow text!", author = nil },
    { text = "1 star! Deal with it notch!", author = nil },
    { text = "Haha, LEL!", author = nil },
    { text = "Play minecraftApp, Watch Topgear, Get Pig!", author = nil },
    { text = "Play Minecraft: PE, Watch Topgear, Get Pig!", author = nil },
    { text = "Play Minecraft, Watch Topgear, Get Pig!", author = nil },
    { text = "OpenGL ES 2.0+!", author = nil },
    { text = "Almost C++14!", author = nil },
    { text = "Almost C++11!", author = nil },
    { text = "MCPE!", author = nil },
    { text = "Made in C++!", author = nil },
    { text = "The Work of Many!", author = nil },
    { text = "Jason! Jason! Jason! Jeison?", author = nil },
    { text = "Verlet integration!", author = nil },
    { text = "Not on Steam!", author = nil },
  }
}
