return {
  { text = "gg", author = "Move to the first line of the file" },
  { text = "G", author = "Move to the last line" },
  { text = "gg=G", author = "Reindent the whole file" },
  { text = "gv", author = "Reselect the last visual selection" },
  { text = "`<", author = "Jump to beginning of last visual selection" },
  { text = "`>", author = "Jump to end of last visual selection" },
  { text = "^", author = "Move to first non-blank character of the line" },
  { text = "g_", author = "Move the last non-blank character of the line (but you remove trailing whitespace, right)" },
  { text = "g_lD", author = "Delete all the trailing whitespace on the line" },
  { text = "ea", author = "Append to the end of the current word" },
  { text = "gf", author = "Jump to the file name under the cursor" },
  { text = "xp", author = "Swap character forward" },
  { text = "Xp", author = "Swap character backward" },
  { text = "yyp", author = "Duplicate the current line" },
  { text = "yapP", author = "Duplicate the current paragraph" },
  { text = "dat", author = "Delete around an HTML tag, including the tag" },
  { text = "dit", author = "Delete inside an HTML tag, excluding the tag" },
  { text = "w", author = "Move one word to the right" },
  { text = "b", author = "Move one word to the left" },
  { text = "dd", author = "Delete the current line" },
  { text = "zc", author = "Close current fold" },
  { text = "zo", author = "Open current fold" },
  { text = "za", author = "Toggle current fold" },
  { text = "zi", author = "Toggle folding entirely" },
  { text = "<<", author = "Outdent current line" },
  { text = ">>", author = "Indent current line" },
  { text = "z=", author = "Show spelling corrections" },
  { text = "zg", author = "Add to spelling dictionary" },
  { text = "zw", author = "Remove from spelling dictionary" },
  { text = "~", author = "Toggle case of current character" },
  { text = "gUw", author = "Uppercase until end of word (u for lower, ~ to toggle)" },
  { text = "gUiw", author = "Uppercase entire word (u for lower, ~ to toggle)" },
  { text = "gUU", author = "Uppercase entire line" },
  { text = "gu$", author = "Lowercase until the end of the line" },
  { text = "da\"", author = "Delete the next double-quoted string" },
  { text = "+", author = "Move to the first non-whitespace character of the next line" },
  { text = "S", author = "Delete current line and go into insert mode" },
  { text = "I", author = "insert at the beginning of the line" },
  { text = "ci\"", author = "Change what’s inside the next double-quoted string" },
  { text = "ca{", author = "Change inside the curly braces (try [, (, etc.)" },
  { text = "vaw", author = "Visually select word" },
  { text = "dap", author = "Delete the whole paragraph" },
  { text = "r", author = "Replace a character" },
  { text = "`[", author = "Jump to beginning of last yanked text" },
  { text = "`]", author = "Jump to end of last yanked text" },
  { text = "g;", author = "Jump to the last change you made" },
  { text = "g,", author = "Jump back forward through the change list" },
  { text = "&", author = "Repeat last substitution on current line" },
  { text = "g&", author = "Repeat last substitution on all lines" },
  { text = "ZZ", author = "Save the current file and close it" },
}
