return {
  format = {
    author_prefix = "",
  },
  quotes = {
    { text = "Extruding Mesh Terrain", author = nil },
    { text = "Balancing Domestic Coefficients", author = nil },
    { text = "Inverting Career Ladder", author = nil },
    { text = "Calculating Money Supply", author = nil },
    { text = "Normalizing Social Network", author = nil },
    { text = "Reticulating Splines", author = nil },
    { text = "Adjusting Emotional Weights", author = nil },
    { text = "Calibrating Personality Matrix", author = nil },
    { text = "Inserting Chaos Generator", author = nil },
    { text = "Concatenating Vertex Nodes", author = nil },
    { text = "Balancing Domestic Coefficients", author = nil },
    { text = "Inverting Career Ladder", author = nil },
    { text = "Mapping Influence Attributes", author = nil },
    { text = "Assigning Mimic Propagation", author = nil },
    { text = "Reticulating Splines", author = nil },
    { text = "Iterating Chaos Array", author = nil },
    { text = "Importing Personality Anchors", author = nil },
    { text = "Inserting Extension Algorithms", author = nil },
    { text = "Concatenating Vertex Nodes", author = nil },
    { text = "Balancing Domestic Coefficients", author = nil },
    { text = "Re-Inverting Career Ladder", author = nil },
    { text = "Mapping Influence Attributes", author = nil },
    { text = "Aggregating Need Agents", author = nil },
    { text = "Reticulating Splines", author = nil },
    { text = "Interpreting Family Values", author = nil },
    { text = "Cabalizing NPC Controls", author = nil },
    { text = "Maximizing Social Network", author = nil },
    { text = "Renewing Urban Combinatorics", author = nil },
    { text = "Redefining Family Values", author = nil },
    { text = "Calibrating Personality Matrix", author = nil },
    { text = "Generating Population Model", author = nil },
    { text = "Homogenizing Interest Anatomy", author = nil },
    { text = "Reticulating Splines", author = nil },
    { text = "Establishing Gift Registry", author = nil },
    { text = "Randomizing Inhabitant Characteristics", author = nil },
    { text = "Readjusting Emotional Weights", author = nil },
    { text = "Activating Hotel Staff", author = nil },
    { text = "Importing Entertainment Talent", author = nil },
    { text = "Updating Vacancy Request Hotline", author = nil },
    { text = "Downloading Weather Data", author = nil },
    { text = "Hyperactivating Children", author = nil },
    { text = "Still Reticulating Splines", author = nil },
    { text = "Updating Hotel Registry", author = nil },
    { text = "Calculating Exchange Rate", author = nil },
    { text = "Activating Deviance Threshold", author = nil },
    { text = "Adapting Behavioral Model", author = nil },
    { text = "Reconfiguring Genetic Algorithms", author = nil },
    { text = "Hybridizing Plant Material", author = nil },
    { text = "Reticulating Splines Again", author = nil },
    { text = "Unfolding Helix Packet", author = nil },
    { text = "Synthesizing Natural Selection", author = nil },
    { text = "Enabling Lot Commercialization", author = nil },
    { text = "Recomputing Mammal Matrix", author = nil },
    { text = "Augmenting Occupational Conduits", author = nil },
    { text = "Initializing Operant Construct", author = nil },
    { text = "Generating Schmoozing Algorithm", author = nil },
    { text = "Populating Empyreal Entities", author = nil },
    { text = "Configuring Studio Operations", author = nil },
    { text = "Reticulating Golden Splines", author = nil },
    { text = "Composing Melodic Euphony", author = nil },
    { text = "Spreading Rumors", author = nil },
    { text = "Polarizing Image Conduits", author = nil },
    { text = "Calibrating Fame Indicant", author = nil },
    { text = "Strengthening Award Foundations", author = nil },
    { text = "Abstracting Loading Procedures", author = nil },
    { text = "Locating Misplaced Calculations", author = nil },
    { text = "Eliminating Would-be Chicanery", author = nil },
    { text = "Tabulating Spell Effectors", author = nil },
    { text = "Reticulating Unreticulated Splines", author = nil },
    { text = "Recycling Hex Decimals", author = nil },
    { text = "Binding Trace Enchantments", author = nil },
    { text = "Fabricating Imaginary Infrastructure", author = nil },
    { text = "Optimizing Baking Temperature", author = nil },
    { text = "Ensuring Transplanar Synergy", author = nil },
    { text = "Simulating Program Execution", author = nil },
    { text = "Reticulating Splines", author = nil },
    { text = "Interpreting Family Values", author = nil },
    { text = "Fabricating Imaginary Infrastructure", author = nil },
    { text = "Recomputing Mammal Matrix", author = nil },
    { text = "Activating Deviance Threshold", author = nil },
    { text = "Composing Melodic Euphony", author = nil },
    { text = "Homogenizing Interest Anatomy", author = nil },
    { text = "Normalizing Social Network", author = nil },
    { text = "Compiling Reticulated Splines", author = nil },
    { text = "Simulating Program Execution", author = nil },
    { text = "Chlorinating Car Pools", author = nil },
    { text = "Partitioning Social Network", author = nil },
    { text = "Prelaminating Drywall Inventory", author = nil },
    { text = "Blurring Reality Lines", author = nil },
    { text = "Reticulating 3-Dimensional Splines", author = nil },
    { text = "Preparing Captive Simulators", author = nil },
    { text = "Capacitating Genetic Modifiers", author = nil },
    { text = "Destabilizing Orbital Payloads", author = nil },
    { text = "Sequencing Cinematic Specifiers", author = nil },
    { text = "Branching Family Trees", author = nil },
    { text = "Manipulating Modal Memory", author = nil },
    { text = "Pressurizing Fruit Punch Barrel Hydraulics", author = nil },
    { text = "Testing Underworld Telecommunications", author = nil },
    { text = "Priming Mascot Mischief Coefficients", author = nil },
    { text = "Caffeinating Student Body", author = nil },
    { text = "Initializing Secret Societies", author = nil },
    { text = "Securing Online Grades Database", author = nil },
    { text = "Reticulating Graduated Splines", author = nil },
    { text = "Requisitioning Alumni Donations", author = nil },
    { text = "Pre-Inking Simoleon Plates", author = nil },
    { text = "Loading School Spirit Algorithm", author = nil },
    { text = "Shampooing Dirty Rugs", author = nil },
    { text = "Restocking Sim Inventories", author = nil },
    { text = "Compositing Vampiric Complexions", author = nil },
    { text = "Replacing Wheel Bearings", author = nil },
    { text = "Re-Re-Re-Re-Re-Reticulating Splines", author = nil },
    { text = "Loading "Vroom " Sounds", author = nil },
    { text = "Turning On Turn-Ons", author = nil },
    { text = "Preparing a Tasty Grilled Cheese Sandwich", author = nil },
    { text = "Infuriating Furious Bits", author = nil },
    { text = "Flavorizing Side-Dishes", author = nil },
    { text = "Disgruntling Employees", author = nil },
    { text = "Managing Managers' Managers", author = nil },
    { text = "Configuring Lemony Squeezation", author = nil },
    { text = "Preparing Bacon for Homeward Transportation", author = nil },
    { text = "Reticulated Splines for Sale: §2000", author = nil },
    { text = "Mitigating Time-Stream Discontinuities", author = nil },
    { text = "Loading "First Batch " Metrics", author = nil },
    { text = "Initializing Forth-Rallying Protocol", author = nil },
    { text = "Neutralizing Shuriken Oxidization", author = nil },
    { text = "Roof = Roof(1/3*pi*r^2*h)", author = nil },
    { text = "Submerging Bedroom Furniture", author = nil },
    { text = "Desalinizing Snorkels", author = nil },
    { text = "Enhancing Crown Reflectivity", author = nil },
    { text = "Crenellating Crenellations", author = nil },
    { text = "Dragon-proofing Dressers", author = nil },
    { text = "Reticulating Underwater Splines", author = nil },
    { text = "Intensifying Hawaiian Prints", author = nil },
    { text = "Navigating Stormy Waters", author = nil },
    { text = "Pre-fluffing Pillows", author = nil },
    { text = "Factoring Fairy Frolicking Frequencies", author = nil },
    { text = "Modeling Marquetry", author = nil },
    { text = "Eschewing Everyday Aesthetics", author = nil },
    { text = "Cultivating Quality and Class", author = nil },
    { text = "Proscribing Plebeian Palates", author = nil },
    { text = "Falsifying Faux Finishes", author = nil },
    { text = "Invigorating Dull Habitations", author = nil },
    { text = "Abolishing Pedestrian Posturing", author = nil },
    { text = "Buffing Splines for Reticulation", author = nil },
    { text = "Appointing Appealing Appurtenances", author = nil },
    { text = "Simulating Sparkling Surfaces", author = nil },
    { text = "Rasterizing Rodent Residences", author = nil },
    { text = "Limiting Litterbox Loads", author = nil },
    { text = "Scheduling Copious Catnaps", author = nil },
    { text = "Calibrating Canine Customization", author = nil },
    { text = "Dumbing Down Doofuses", author = nil },
    { text = "Scolding Splines for Reticulating", author = nil },
    { text = "Distilling Doggie Dynamics", author = nil },
    { text = "Atomizing Atomic Particles", author = nil },
    { text = "Decrementing Feline Life-Count", author = nil },
    { text = "Dampening Stray Generators", author = nil },
    { text = "Gleefully Stacking Inventories", author = nil },
    { text = "De-chlorophyllizing Leaves", author = nil },
    { text = "Predicting Puddle Prevalence", author = nil },
    { text = "Calculating Snowball Trajectories", author = nil },
    { text = "Unexpectedly Reticulating Splines", author = nil },
    { text = "Assessing Loam Particle Sizes", author = nil },
    { text = "Timing Temperature Transference", author = nil },
    { text = "Individualizing Snowflakes", author = nil },
    { text = "Hydrating Harvestables", author = nil },
    { text = "Stocking Ponds", author = nil },
    { text = "Reverse-Engineering Party Scores", author = nil },
    { text = "Unfolding Foldy Chairs", author = nil },
    { text = "Rehearsing Dinner", author = nil },
    { text = "Crash-Proofing Parties", author = nil },
    { text = "Grooming Grooms", author = nil },
    { text = "Mingling", author = nil },
    { text = "De-inviting Don Lothario", author = nil },
    { text = "Borrowing Something Blue", author = nil },
    { text = "Happy 14th Birthday Reticulated Splines!", author = nil },
    { text = "Applying Lampshade Headwear", author = nil },
    { text = "Stocking Clearance Racks", author = nil },
    { text = "Fiercely Reticulating Splines", author = nil },
    { text = "Fashioning Late Arrivals", author = nil },
    { text = "De-wrinkling Worry-Free Clothing", author = nil },
    { text = "Distressing Jeans", author = nil },
    { text = "Developing Delicious Designs", author = nil },
    { text = "Formulating Fitting Rooms", author = nil },
    { text = "Tailoring Trendy Threads", author = nil },
    { text = "Constructing Clothes Hangers", author = nil },
    { text = "Adjusting Acceptable Apparel", author = nil },
    { text = "Readying Relaxation Receptors", author = nil },
    { text = "Predicting Pagoda Peaks", author = nil },
    { text = "Originating Ocean Currents", author = nil },
    { text = "Faceting Precious Gems", author = nil },
    { text = "Preparing Vacation Days", author = nil },
    { text = "Spawning Sights to See", author = nil },
    { text = "Reticulating Ninja Splines", author = nil },
    { text = "Analyzing Axe Trajectories", author = nil },
    { text = "Training Tour Guides", author = nil },
    { text = "Initializing Dastardly Schemes", author = nil },
    { text = "Capturing Youthful Exuberance", author = nil },
    { text = "Analyzing Adolescent Angst", author = nil },
    { text = "Preparing Personal Spaces", author = nil },
    { text = "Making a Mess", author = nil },
    { text = "Like, Totally Reticulating Splines, Dude", author = nil },
    { text = "Generating Gothic Glamour", author = nil },
    { text = "Monitoring Moody Minors", author = nil },
    { text = "Sweetening Sixteens", author = nil },
    { text = "Teasing Teenage Hair-dos", author = nil },
    { text = "Building Boring Bedrooms? As If!", author = nil },
    { text = "Factoring Hobby Enthusiasm", author = nil },
    { text = "Calculating Lifetime Aspirations", author = nil },
    { text = "Predicating Predestined Paths", author = nil },
    { text = "Populating Yards with Bugs and Birds", author = nil },
    { text = "Writing Scrolling Startup String Text", author = nil },
    { text = "Reticulating Splines in the Zone", author = nil },
    { text = "Recruiting Snooty Food Judges", author = nil },
    { text = "Breaking Down Restorable Cars", author = nil },
    { text = "Threading Sewing Needles", author = nil },
    { text = "Lacing Football Cleats", author = nil },
    { text = "Taking Countertops for Granite", author = nil },
    { text = "Preparing Perfect Plumbing", author = nil },
    { text = "Baking Bread for Toasters", author = nil },
    { text = "Igniting Pilot Lights", author = nil },
    { text = "Putting Down Toilet Seats", author = nil },
    { text = "Remodeling Spline Reticulator", author = nil },
    { text = "Assembling Shower Stalls", author = nil },
    { text = "Examining Tiles from All Zooms and Angles", author = nil },
    { text = "Cooling Down Refrigerators", author = nil },
    { text = "Stocking Stylish Sinks", author = nil },
    { text = "Creating Handmade Lampshades", author = nil },
    { text = "Making Many Mini Wrenches", author = nil },
    { text = "Supplying Self-Serve Furniture Area", author = nil },
    { text = "Simmering Swedish Meatballs", author = nil },
    { text = "Building Bedroom Displays", author = nil },
    { text = "Stress-Testing POÄNG Chairs", author = nil },
    { text = "Some Spline Reticulating Required", author = nil },
    { text = "Upholstering Sofas and Loveseats", author = nil },
    { text = "Boxing BILLY Bookcases", author = nil },
    { text = "Spooling IKEA Awesomeness", author = nil },
    { text = "Going Apartment Hunting", author = nil },
    { text = "Determining Rent Guidelines", author = nil },
    { text = "Preparing for Pops and Locks", author = nil },
    { text = "Generating Compatible Roommates", author = nil },
    { text = "Twisting Spiral Staircases", author = nil },
    { text = "Telling Splines to Reticulate More Quietly", author = nil },
    { text = "Making a Little Bit of Magic", author = nil },
    { text = "Rasterizing Reputation Algorithms", author = nil },
    { text = "Cluttering Closets", author = nil },
    { text = "Perfecting Playground Pieces", author = nil },
    { text = "Growing Greener Gardens", author = nil },
    { text = "Making Manic Mansions", author = nil },
    { text = "Storing Solar Energy", author = nil },
    { text = "Over-Waxing Banisters", author = nil },
    { text = "Stopping To Smell The Flowers", author = nil },
    { text = "Extrapolating Empire Eigenvectors", author = nil },
    { text = "Ceiling Fan Rotation = dL/dT", author = nil },
    { text = "Increasing Water Plant Population", author = nil },
    { text = "Redistributing Resources", author = nil },
    { text = "Reticulating Splines One Last Time", author = nil },
    { text = "Reticulating Story Splines", author = nil },
    { text = "Matching Walls and Floors", author = nil },
    { text = "Partitioning Prose", author = nil },
    { text = "Canceling Un-cancelable Actions", author = nil },
    { text = "Filling in the Blanks", author = nil },
    { text = "Enforcing Storyline", author = nil },
    { text = "Generating Intrigue", author = nil },
    { text = "Launching SimSat 9000", author = nil },
    { text = "Compiling Riley's Wardrobe", author = nil },
    { text = "Calculating Vincent's Wealth", author = nil },
    { text = "Activating Story Arc", author = nil },
    { text = "Re-Activating Story Arc", author = nil },
    { text = "Leveling Playing Fields", author = nil },
    { text = "Stooping and Scooping", author = nil },
    { text = "Making Pets Look Like Owners", author = nil },
    { text = "Making Owners Look Like Pets", author = nil },
    { text = "Reticulating Dog Show Object Splines", author = nil },
    { text = "Delineating Mask Dynamics", author = nil },
    { text = "Reinforcing Story Lines", author = nil },
    { text = "Decrementing Alice's Funds", author = nil },
    { text = "Making Stephen Loyal", author = nil },
    { text = "Calculating Native Restlessness", author = nil },
    { text = "Transmitting Message Bottles", author = nil },
    { text = "Clearing Shipping Lanes", author = nil },
    { text = "Severing Civilization Connections", author = nil },
    { text = "Generating Sand Grains", author = nil },
    { text = "Bribing The Orangutans", author = nil },
    { text = "Wrangling All Wreckage", author = nil },
    { text = "Predicting Weather Unpredictability", author = nil },
    { text = "Estimating Volcanic Activity", author = nil },
    { text = "Amplifying Sun to '11'", author = nil },
    { text = "Expanding Horizons...", author = nil },
    { text = "Unloading Loading Screens...", author = nil },
    { text = "Mediating Modifiers...", author = nil },
    { text = "Reticulating 4-D Splines...", author = nil },
    { text = "Ascending Maslow's Hierarchy...", author = nil },
    { text = "Mapping the Llama Genome...", author = nil },
    { text = "Tabulating Traits...", author = nil },
    { text = "Calibrating Social Distance...", author = nil },
    { text = "Threading Fabric Compositors...", author = nil },
    { text = "Texture-Compositing Teddy Bears...", author = nil },
    { text = "Stomping Grapes...", author = nil },
    { text = "Trading Shawarma for Information...", author = nil },
    { text = "Finding Mummitomium...", author = nil },
    { text = "Haggling The Final Details...", author = nil },
    { text = "Seeking Adventure...", author = nil },
    { text = "Surviving Vaughan’s Tomb...", author = nil },
    { text = "Creating-a-Crepe...", author = nil },
    { text = "Check Out My Awesome Belt...", author = nil },
    { text = "Sim Fu: Jumping Kicks...", author = nil },
    { text = "Beware the spitting dragon...", author = nil },
    { text = "Redesigning the Space…", author = nil },
    { text = "Living It Up…", author = nil },
    { text = "Building High Ceilings…", author = nil },
    { text = "Upgrading Gadgets…", author = nil },
    { text = "Activating LED lights…", author = nil },
    { text = "Styling Hair…", author = nil },
    { text = "Spinning New Tunes…", author = nil },
    { text = "Anticipating the Good Life…", author = nil },
    { text = "Polishing Glass and Metal…", author = nil },
    { text = "Calculating Deck Size…", author = nil },
    { text = "Subduing Washing Machines…", author = nil },
    { text = "Scrapping Inventions…", author = nil },
    { text = "Intercepting Meteorites...", author = nil },
    { text = "Vaccinating Sims…", author = nil },
    { text = "Resolving Temporal Paradoxes…", author = nil },
    { text = "Decapitating Topiaries…", author = nil },
    { text = "Tattooing Bellybuttons…", author = nil },
    { text = "Dusting for Prints…", author = nil },
    { text = "Decreasing Fire Safety…", author = nil },
    { text = "Sneaking Cookie Dough…", author = nil },
    { text = "Revving Engines…", author = nil },
    { text = "Adjusting Mirrors…", author = nil },
    { text = "Conserving Fuel…", author = nil },
    { text = "Calibrating Speedometers…", author = nil },
    { text = "Deploying Air Freshener…", author = nil },
    { text = "Calculating Maximum Velocity…", author = nil },
    { text = "Realigning Splines…", author = nil },
    { text = "Injecting Fuel…", author = nil },
    { text = "Checkering Flags…", author = nil },
    { text = "Buckling Up…", author = nil },
    { text = "Applying Racing Stripes…", author = nil },
    { text = "Greasing Hair…", author = nil },
    { text = "Hiding Swimsuits...", author = nil },
    { text = "Fueling Food Trucks...", author = nil },
    { text = "Tickling the Ivories...", author = nil },
    { text = "Replenishing Plasma...", author = nil },
    { text = "Sterilizing Hot Tubs...", author = nil },
    { text = "Mixing, Shaking, Igniting...", author = nil },
    { text = "Augmenting Assets...", author = nil },
    { text = "Deflecting Scandals...", author = nil },
    { text = "Sneaking Past Bouncers...", author = nil },
    { text = "Dusting Shuffleboards...", author = nil },
    { text = "Disguising Outdoor Stereos...", author = nil },
    { text = "Firing Up the Barbeque...", author = nil },
    { text = "Applying Sunscreen...", author = nil },
    { text = "Squeezing Lemons...", author = nil },
    { text = "Nurturing Terrariums...", author = nil },
    { text = "Hiding Garden Gnomes...", author = nil },
    { text = "Stocking Mini-Fridge...", author = nil },
    { text = "Padding Deck Chairs...", author = nil },
    { text = "Opening Umbrellas...", author = nil },
    { text = "Lighting Votives...", author = nil },
    { text = "Polishing BBQ Utensils...", author = nil },
    { text = "Planning Dinosaur Rampage...", author = nil },
    { text = "Unrolling Sleeping Bags...", author = nil },
    { text = "Stacking Bunk Beds...", author = nil },
    { text = "Timing Mood Swings...", author = nil },
    { text = "Concocting Ghost Stories...", author = nil },
    { text = "Balancing Seesaws...", author = nil },
    { text = "Whittling Canes...", author = nil },
    { text = "Catalyzing Chemicals...", author = nil },
    { text = "Besmirching Reputations...", author = nil },
    { text = "Remembering the Good Old Days...", author = nil },
    { text = "Capturing Family Moments...", author = nil },
    { text = "Sparking Imaginations...", author = nil },
    { text = "Boosting Detergent", author = nil },
    { text = "Sizing Shirt Collars", author = nil },
    { text = "Adjusting Incline", author = nil },
    { text = "Curling Dumbells", author = nil },
    { text = "Stacking Books", author = nil },
    { text = "Waxing Slide Surface", author = nil },
    { text = "Alphabetizing Books", author = nil },
    { text = "Climbing Treehouses", author = nil },
    { text = "Folding Towels", author = nil },
    { text = "Pumping Iron", author = nil },
    { text = "Digitizing Novels", author = nil },
    { text = "Assembling Playground", author = nil },
    { text = "Burning Calories", author = nil },
    { text = "Boosting Bark Volume...", author = nil },
    { text = "Emptying Litter Boxes...", author = nil },
    { text = "Carpeting Cat Condos...", author = nil },
    { text = "Reticulating Tail Splines...", author = nil },
    { text = "Sharpening Unicorn Horns...", author = nil },
    { text = "Saddling Up...", author = nil },
    { text = "Allocating Canine Loyalty...", author = nil },
    { text = "Calibrating Claws...", author = nil },
    { text = "Hatching Fleas...", author = nil },
    { text = "Wagging Tails...", author = nil },
    { text = "Fluffing Pillows...", author = nil },
    { text = "Freshening Up...", author = nil },
    { text = "Scattering Rose Petals...", author = nil },
    { text = "Spraying Perfume...", author = nil },
    { text = "Lighting Candles...", author = nil },
    { text = "Straightening Mirrors...", author = nil },
    { text = "Arranging Flowers...", author = nil },
    { text = "Dimming Lights...", author = nil },
    { text = "Drawing a Bath...", author = nil },
    { text = "Getting Comfortable...", author = nil },
    { text = "Trying to Escape the Invisible Box...", author = nil },
    { text = "Finalizing Dreams...", author = nil },
    { text = "Feeding the Mechanical Bull...", author = nil },
    { text = "Stuffing Genies into Bottles...", author = nil },
    { text = "Inventing Internets...", author = nil },
    { text = "Determining Starfish Populations...", author = nil },
    { text = "Performing a Sound Check...", author = nil },
    { text = "Warming up the Audience...", author = nil },
    { text = "Appeasing Divas...", author = nil },
    { text = "Practicing Air Guitar...", author = nil },
    { text = "Whipping Cream", author = nil },
    { text = "Adding Food Dye", author = nil },
    { text = "Spinning Sugar", author = nil },
    { text = "Frosting Cupcakes", author = nil },
    { text = "Sculpting Fondant", author = nil },
    { text = "Sugaring Plums", author = nil },
    { text = "Icing Cookies", author = nil },
    { text = "Licking Lollipops", author = nil },
    { text = "Lighting Fireworks", author = nil },
    { text = "Swirling Frosting", author = nil },
    { text = "Stitching Denim", author = nil },
    { text = "Fitting Attitudes", author = nil },
    { text = "Pioneering New Styles", author = nil },
    { text = "Redefining Casual", author = nil },
    { text = "Exploring Self-Expression", author = nil },
    { text = "Making Statements", author = nil },
    { text = "Embracing Lifestyle", author = nil },
    { text = "Looking Good", author = nil },
    { text = "Taking Dares", author = nil },
    { text = "Challenging Normal", author = nil },
    { text = "Brewing Elixirs...", author = nil },
    { text = "Preparing Untold Fortunes...", author = nil },
    { text = "Verifying Existence of Fairies...", author = nil },
    { text = "Braaaains...", author = nil },
    { text = "Reading Palms...", author = nil },
    { text = "Asking the Mirror...", author = nil },
    { text = "Planting Jelly Bean Seeds...", author = nil },
    { text = "Determining Moon Phase...", author = nil },
    { text = "Polishing Wands...", author = nil },
    { text = "Instantiating Werewolf Claws...", author = nil },
    { text = "Tricking Out Magic Brooms...", author = nil },
    { text = "Coloring Leaves…", author = nil },
    { text = "Seeding Clouds…", author = nil },
    { text = "Setting World Thermostat…", author = nil },
    { text = "Salting Streets…", author = nil },
    { text = "Planting Wildflowers…", author = nil },
    { text = "Spreading Holiday Cheer…", author = nil },
    { text = "Hiding Eggs…", author = nil },
    { text = "Casting Sun Rays…", author = nil },
    { text = "Volumizing Fog…", author = nil },
    { text = "Cutting Out Snowflakes…", author = nil },
    { text = "Feathering Hair", author = nil },
    { text = "Putting Baby in a Corner", author = nil },
    { text = "Stretching Spandex", author = nil },
    { text = "Grunging It Up", author = nil },
    { text = "Shaggin Carpets", author = nil },
    { text = "Reticulating Plaid", author = nil },
    { text = "Acid Washing Everything", author = nil },
    { text = "Unpacking Brats", author = nil },
    { text = "Taking It to the Max!", author = nil },
    { text = "Following Dance Safety Protocols", author = nil },
    { text = "Cramming Knowledge…", author = nil },
    { text = "Skipping Classes…", author = nil },
    { text = "Populating Social Groups…", author = nil },
    { text = "Printing Text Books…", author = nil },
    { text = "Protesting Loading Screens…", author = nil },
    { text = "Training Mascots…", author = nil },
    { text = "Pixelating Streakers…", author = nil },
    { text = "Calculating GPA…", author = nil },
    { text = "Photosynthesizing…", author = nil },
    { text = "Forming Study Groups…", author = nil },
    { text = "Calculating Wave Functions…", author = nil },
    { text = "Running In Slow Motion…", author = nil },
    { text = "Scraping Barnacles…", author = nil },
    { text = "Measuring Ocean Depth…", author = nil },
    { text = "Debugging Rooms…", author = nil },
    { text = "Releasing The Kraken…", author = nil },
    { text = "Filling Oxygen Tanks…", author = nil },
    { text = "Chlorinating Pools…", author = nil },
    { text = "Hiding Islands…", author = nil },
    { text = "Polishing Mermaid Scales…", author = nil },
    { text = "Burying Treasure…", author = nil },
    { text = "Hoisting The Anchor…", author = nil },
    { text = "Adjusting Lighting...", author = nil },
    { text = "Calibrating Cameras...", author = nil },
    { text = "Hailing Heroes...", author = nil },
    { text = "Wandering West...", author = nil },
    { text = "Spinning Webs...", author = nil },
    { text = "Reeling Film...", author = nil },
    { text = "Vilifying Villains...", author = nil },
    { text = "Spooking Sims...", author = nil },
    { text = "Sound Checking Splines…", author = nil },
    { text = "Painting Backdrops...", author = nil },
    { text = "Synthesizing Recipes...", author = nil },
    { text = "Calibrating Nanites...", author = nil },
    { text = "Integrating Trait Chips...", author = nil },
    { text = "Bending Time and Space...", author = nil },
    { text = "Charging Plumbots...", author = nil },
    { text = "Materializing Holographs...", author = nil },
    { text = "Repairing Time Continuum...", author = nil },
    { text = "Engaging Tube Elevators...", author = nil },
    { text = "Automating Plumbots...", author = nil },
    { text = "Measuring Singularity...", author = nil },
  }
}
